### ISSUE TITLE
Ability to zoom or focus on image

### ISSUE THREAD

**Issue by lalitsom** [lalitsom/xkcd#2]
Tried [Material box](http://materializecss.com/media.html) for this feature but not able to make it work.

**Comment by skyspy20** [comment]
Hello
Can you send me some details about the thing you want to do??

**Comment by lalitsom** [comment]
Hi @skyspy20 ,
You could try opening this [link](http://materializecss.com/media.html). it will give you an idea on what I'm trying to achieve. If a user clicks (or tap) on an image it should pop up on fullscreen (just like how twitter does it).
you could use css classes from materialize.css which is already embeded in website.

**Comment by lalitsom** [comment]
issue is solved in pull request #3
